### ISSUE TITLE
Error from Catch

### ISSUE THREAD

**Issue by moovida** [moovida/smash#73]
Error:

Bad state: Stream has already been listened to.

Stack trace:

#0 _StreamController._subscribe (dart:async/stream_controller.dart:710)
#1 _ControllerStream._createSubscription (dart:async/stream_controller.dart:860)
#2 _StreamImpl.listen (dart:async/stream_impl.dart:493)
#3 GpsHandler.init (package:smash/eu/hydrologis/smash/gps/gps.dart:240)

#4 ProjectView.initGps (package:smash/eu/hydrologis/smash/project/projects_view.dart:230)

#5 ProjectView.build.. (package:smash/eu/hydrologis/smash/project/projects_view.dart:154)

**Comment by moovida** [comment]
Fixed
