### ISSUE TITLE
[CATCHER] Error report: >> Bad state: Not writing over existing file.

### ISSUE THREAD

**Issue by moovida** [moovida/smash#91]
```
Error:

Bad state: Not writing over existing file.

Stack trace:

#0 GeopackageExporter.exportDb (package:smash/eu/hydrologis/smash/export/geopackage_export.dart:22)

#1 _ExportWidgetState.buildGeopackage (package:smash/eu/hydrologis/smash/export/export_widget.dart:65)

#2 _ExportWidgetState.build. (package:smash/eu/hydrologis/smash/export/export_widget.dart:193)


Device parameters:

id: R16NW
androidId: 1eb1e968c574129f
board: universal8890
bootloader: G930FXXU8ETI2
brand: samsung
device: herolte
display: R16NW.G930FXXU8ETI2
fingerprint: samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXU8ETI2:user/release-keys
hardware: samsungexynos8890
host: 21HHAG24
isPhysicalDevice: true
manufacturer: samsung
model: SM-G930F
product: heroltexx
tags: release-keys
type: user
versionBaseOs:
versionCodename: REL
versionIncremental: G930FXXU8ETI2
versionPreviewSdk: 0
versionRelease: 8.0.0
versionSdk: 26
versionSecurityPatch: 2020-09-01

Application parameters:

environment: release
version: 1.6.2
appName: SMASH
buildNumber: 49
packageName: eu.hydrologis.smash
```

**Comment by moovida** [comment]
fixed
