### ISSUE TITLE
[CATCHER] Error report: >> PlatformException(photo_access_denied, The user did not allow photo access

### ISSUE THREAD

**Issue by moovida** [moovida/smash#94]
Error:
PlatformException(photo_access_denied, The user did not allow photo access., null, null)

Stack trace:
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)

#2 ImagePicker.pickImage (package:image_picker/image_picker.dart:61)

#3 Camera.loadImageFromGallery (package:smashlibs/com/hydrologis/flutterlibs/camera/camera.dart:27)

#4 SmashFormHelper.takePictureForForms (package:smash/eu/hydrologis/smash/forms/form_smash_utils.dart:42)

#5 PicturesWidgetState.build. (package:smashlibs/com/hydrologis/flutterlibs/forms/forms_widgets.dart:1116)

Device parameters:
model: iPhone
isPhysicalDevice: true
name: Arnes iphone
identifierForVendor: 3C8E1F4E-A86E-4EE3-96F9-26ACEE4CBD95
localizedModel: iPhone
systemName: iOS
utsnameVersion: Darwin Kernel Version 20.1.0: Fri Oct 30 00:34:17 PDT 2020; root:xnu-7195.42.3~1/RELEASE_ARM64_T8020
utsnameRelease: 20.1.0
utsnameMachine: iPhone11,8
utsnameNodename: Arnes-iphone
utsnameSysname: Darwin

Application parameters:
environment: release
version: 1.6.2
appName: null
buildNumber: 49
packageName: eu.hydrologis.smash

**Comment by moovida** [comment]
Never appeared again, closing
